### ISSUE TITLE
[Enhancement] Item Frame Support for States

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/AdvancedMobArena-spigot#10]
I am working on an elevator map, and I am using states to swap between all the different floors, one of the floors looks like picture one, but without item frames, it will look like picture two but without the item frames there.

Item frames are a great building tool and it would be a shame to not be able to utilize them with such a powerful feature

![2023-10-17-19-36-16](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/3754909/b344dc90-f33d-4842-be43-140a37eb48bc)

![2023-10-17-09-27-44](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/3754909/641e2cc6-5a2f-47ac-9d20-1746ccc4a563)

**Comment by nulli0n** [comment]
No way currently, unfortunately. Item frames are entities, and spot states can save only blocks in their schematics.
