### ISSUE TITLE
[QOL Enhancement] Mob head to represent mobs in wave editor

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/AdvancedMobArena-spigot#11]
All the item heads are zombie heads, it makes it hard to tell whats what at a glance
It would be nice for them to use their base mobs head when provided by AMA at least, and maybe have the icon configurable, its not a big deal but it would look cleaner

![image](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/3754909/db7c81cb-e76d-4597-bff1-0be11fba4cac)

**Comment by nulli0n** [comment]
Done in v7.11.0
