### ISSUE TITLE
[QOL Enhancement] Configurable icons for arenas in Arena editor

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/AdvancedMobArena-spigot#12]
Its hard to tell what arena is what at a glance, which becomes a problem the more arenas you get

![image](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/3754909/8108ffea-1e63-4a14-95f0-2dcfa8f3c7ee)

**Comment by nulli0n** [comment]
Done in v7.11.0
