### ISSUE TITLE
[Bug] Spots not keeping Banner and player head data

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/AdvancedMobArena-spigot#13]
When loading a state that has custom player heads and banners in it, it does not keep the skin hash, or the banner patterns

**Comment by nulli0n** [comment]
Confirmed. Unfortunately, there is no way to fix this currently, since some block data is not available for serialization via API. I'll see if there are any workarounds for that.

**Comment by LadyHaley** [comment]
#10 
Would you consider hooking into world edit and or FAWE to handle the spot saving and loading
It already handles entities, banner data and player head data and would solve both tickets
