### ISSUE TITLE
Unable to teleport to the spawn world

### ISSUE THREAD

**Issue by xiaolu1926** [nulli0n/AdvancedMobArena-spigot#16]
I have set up setspawn and mvsetspawn in a world, which is my main city. However, after loading the AdvancedMobArena plugin, ordinary players cannot return to the main city through spawn commands or transfer to the main city world through a series of transmission methods such as home back tpa tpall. My server uses the 1.20.2 version of the paper plugin, which is also the latest version

**Comment by nulli0n** [comment]
Fixed in the latest update.
