### ISSUE TITLE
gameplay settings wrong

### ISSUE THREAD

**Issue by XiongGaPuo** [nulli0n/AdvancedMobArena-spigot#17]
Other players cannot join the arena when the kits option in gameplay settings is set to No

![image](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/53654069/beb86498-8972-4705-8f0a-ece50176ea8f)
![image](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/53654069/6c27a0d4-d78f-43f4-974b-55d653b9df54)
![image](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/53654069/dd4ae2bd-41c6-409e-abc2-4b86609115ee)
![image](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/53654069/ca4b09ec-e284-47de-b015-3db97517bd1b)

**Comment by nulli0n** [comment]
Fixed
