### ISSUE TITLE
DecentHologrames

### ISSUE THREAD

**Issue by dinobossytnew** [nulli0n/AdvancedMobArena-spigot#19]
Now with Decenthologrames it's easier to get clicks, so now it would be possible to make holograms that click and performance improvements in your plugin. I think you should be able to check so you could add this function as compatible

**Comment by dinobossytnew** [comment]
https://wiki.decentholograms.eu/api/events/ 

getPlayer() - Gets the Player that clicked the hologram.
getHologram() - Gets the hologram that has been clicked.
getHologramPage() - Gets the HologramPage that has been clicked.
getClickType() - Gets the click type (Whether it was left or right click and whether the player sneaked while clicking).
getEntityId() - Gets the ID of the clicked entity.

**Comment by nulli0n** [comment]
I think we will replace holograms with custom solution in near future.

**Comment by dinobossytnew** [comment]
ok
