### ISSUE TITLE
[Bug] Mobs not spawned by AMA having some problems

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/AdvancedMobArena-spigot#2]
I have an item that spawns in an iron golem that fights for the player. previously there was the issue of iron golems attacking the player, so you added last year a fix that lets mythic mobs with custom targeting AI not get changed by AMA, which works. but the Iron Golem cannot attack arena mobs still, and it still gets added to the arena mob total even tho it is supposed to be an ally mob, not a foe

**Comment by LadyHaley** [comment]
My main config has this in it, and that is the correct mob name
`Mobs:
  Ally_Mythic_Mobs:
  - AMAFGolemFriend`

**Comment by nulli0n** [comment]
Is it still relevant?

**Comment by SawJin22** [comment]
yes, still having this issues with mmocore allied mobs that are summoned by classes, allied mobs cannot do damage to anything inside the arena
