### ISSUE TITLE
[Bug] Cant spawn mobs or entities on a disabled arena

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/AdvancedMobArena-spigot#3]
When my arena is disabled, I am unable to spawn any mobs into the arena region, this means in order to make changes to or set up my map using custom mobs to control certain aspects of it, i need to flat out disable mob arena while I do my work on one map, and then restart the server when i am done. Could you please fix it so I can spawn mobs when the arena is disabled

**Comment by LadyHaley** [comment]
I have custom spawn conditions set that do work during a game, but when a game is not running, i cannot spawn mobs at all

**Comment by LadyHaley** [comment]
in the arena config file I have the spawn reasons defined
`Allowed_Spawn_Reasons:
- MOUNT
- COMMAND
- REINFORCEMENTS
- CUSTOM
- SPAWNER_EGG
- BREEDING`
but its not allowing me to spawn mobs when the arena is disabled.

**Comment by nulli0n** [comment]
Should be fixed in the latest version.
